### ISSUE TITLE
Issues when accessing invalid sound bank

### ISSUE THREAD

**Issue by simoninns** [simoninns/TMS6100-Emulator#7]
On the BBC micro issuing the following commands:

SOUND -1,160,0,0
SOUND -2,160,0,0
SOUND -1,160,0,0

Should produce "Acorn", silence, "Acorn".  Instead the final sound command isn't successful (and the computer refuses to speak again until the machine has be reset).

**Comment by simoninns** [comment]
This was fixed a while ago... I forgot to close the issue.

**Comment by kgl2001** [comment]
I'm still seeing this problem, with both the 2.3 release, and with a self compiled version from the latest master. Is there something else I need to do to resolve this problem?

**Comment by simoninns** [comment]
I'll have to double-check the implementation and see if this can be reproduced.
